### PR TITLE
Fixed #188: Update Google Test to 1.9

### LINKED ISSUE #188: Update Google Test to 1.9
Google Test 1.8, which is used for blackhole, produces a lot warning when being build with Visual Studio 2017. Version 1.9 does build without any warnings.

Only potential drawback, starting with 1.9 Google Test won't release any new version and is following the [Abseil Live at Head](https://abseil.io/about/philosophy) philosophy. 

During my port to Windows project, I'd like to update Google Test to 1.9.

### PR DESCRIPTION
**Pull request by Maturin**

### CODE REVIEW

**Comment by Maturin** [comment]
Shippable has a problem with compiling Google Test 1.9. I don't know which cmake version, they are using. At [console log](https://app.shippable.com/github/3Hren/blackhole/runs/430/1/console) I could only see cmake 2.8. That might be a problem. Google Test requires 2.8.8. 

blackholes cmake minimum requirement is 2.6 right now. Unfortunately I was using cmake 3.12.4, so I didn't noticed this problem before.

@3Hren Do you have some requirements, which prevents us from changing the minimum cmake version for blackhole?

**Comment by 3Hren** [comment]
AFAIK, cmake 2.6 is the maximum version on Ubuntu 14.04, which is being used by guys I wrote this library. Maybe, it's already not.

@shaitan can you tell us about platforms Blackhole is used on now, please?

**Comment by shaitan** [comment]
We still have Ubuntu 14.04, but the highest available version of cmake is `2.8.12.2-0ubuntu3`. So minimum requirement could be updated to `2.8.8`.

**Comment by Maturin** [comment]
I investigated this issue a little bit more. The Google Test CMakeLists.txt states that the minimum requirement is 2.6.2, but this is actually wrong. The minimum requirement is 3.0.0 and an [issue](https://github.com/abseil/googletest/issues/1787) exist for changing this. 

My tests showed that Google Test 1.8.0 is the last version, which builds with pre 3.0.0 cmake versions, 1.8.1 fails already. 

Since Ubuntu 14.04 with cmake 2.8.12 is a hard requirement and thus, Google Test 1.8.0, I added a cmake version check. With cmake before 3.0.0 Google Test 1.8.0 is used and with cmake after 3.0.0 the latest Google Test version is used.

**Comment by 3Hren** [comment]
Sorry for the long reply. LGTM!

**Pull request merged**
