### PR TITLE
v1.7.0

### PR DESCRIPTION
**Pull request by 3Hren**
ABI report: [compatible](https://cdn.rawgit.com/3Hren/blackhole/abi/0799f7659a35e6efd930db880606e91315c52f4f-60578d65c962b26acdcac265bb1d821ea845b776.html).

### CODE REVIEW

**Comment by shaitan** [comment]
How to specify **overflow policy** by `builder<asynchronous_t>`?

**Comment by 3Hren** [comment]
Will add.

**Comment by shaitan** [comment]
thnx

**Comment by 3Hren** [comment]
Done.

**Pull request merged**
